# Generated by Django 4.0.4 on 2022-04-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TDSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TDTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawline', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('transid', models.CharField(db_index=True, max_length=15, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('qty', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('commision', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.tdsymbol')),
            ],
        ),
    ]
