# Generated by Django 4.0.4 on 2022-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('transid', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('qty', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('commision', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('rawline', models.TextField(blank=True, null=True)),
                ('converted', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
